name: Action Package Run

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - 'runner-**'
      - 'feature-**'
      - 'runner/**'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./
      with:
        email: ${{ secrets.CLOUDWAYS_EMAIL }}
        api-key: ${{ secrets.CLOUDWAYS_API_KEY }}
        # api-version: "v1"
        api-path: "/regions"
        request-method: "GET"
        request-body: ""
        token-required: true

    - name: Response
      # env:
        # cwResponse: ""
      run: |
        echo "cwResponse: $cwResponse"
